name: Release-Build

daon: [push]
s
edanv:
  BdaUILD_TYPE: Release
sd
joadbs:
  buaild:
    rdauns-on: windows-latest
das
    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Display current directory
      run: dir
      shell: cmd
    - name: Display Qt directory
      run: dir ..\Qt
      shell: cmd

    - name: Build source
      run: MSBuild Project.sln /p:Configuration=Release
